/*INSERT INTO Counselor (USERNAME, PASSWORD, NAME, CREATED_DATE) VALUES ('test1', 'test1', '테스트1', CURRENT_TIMESTAMP());
INSERT INTO Counselor (USERNAME, PASSWORD, NAME, CREATED_DATE) VALUES ('test2', 'test2', '테스트2', CURRENT_TIMESTAMP());
INSERT INTO Counselor (USERNAME, PASSWORD, NAME, CREATED_DATE) VALUES ('test3', 'test3', '테스트3', CURRENT_TIMESTAMP());

INSERT INTO Inquiry (CUSTOMER_ID, TITLE, CONTENT, CREATED_DATE) VALUES ('test_customer1', '문의 드립니다. 1', 'TEST1', CURRENT_TIMESTAMP());*/

INSERT INTO Counselor (USERNAME, PASSWORD, NAME, CREATED_DATE) VALUES ('test1', '1234', '테스트1', CURRENT_TIMESTAMP());
INSERT INTO Counselor (USERNAME, PASSWORD, NAME, CREATED_DATE) VALUES ('test2', '1234', '테스트2', CURRENT_TIMESTAMP());
INSERT INTO Counselor (USERNAME, PASSWORD, NAME, CREATED_DATE) VALUES ('test3', '1234', '테스트3', CURRENT_TIMESTAMP());
INSERT INTO Counselor (USERNAME, PASSWORD, NAME, CREATED_DATE) VALUES ('test3', '1234', '테스트4', CURRENT_TIMESTAMP());


INSERT INTO Inquiry (CUSTOMER_ID, TITLE, CONTENT, CREATED_DATE) VALUES ('test1', '문의 드립니다. 1', 'TEST1', CURRENT_TIMESTAMP());
INSERT INTO Inquiry (CUSTOMER_ID, TITLE, CONTENT, CREATED_DATE) VALUES ('test2', '문의 드립니다. 2', 'TEST2', CURRENT_TIMESTAMP());
INSERT INTO Inquiry (CUSTOMER_ID, TITLE, CONTENT, CREATED_DATE) VALUES ('test3', '문의 드립니다. 3', 'TEST3', CURRENT_TIMESTAMP());
INSERT INTO Inquiry (CUSTOMER_ID, TITLE, CONTENT, CREATED_DATE) VALUES ('test4', '문의 드립니다. 4', 'TEST4', CURRENT_TIMESTAMP());